### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by sheik-mostafizur** [edust-org/edust#1]
Design and work on this issue for authentication.

**Comment by sheik-mostafizur** [comment]
### Create a sign-in page design

![Image](https://github.com/edust-org/edust/assets/106415501/22c4aa23-65f5-4e0b-8b5c-0a46ac426e8c)


### Create a sign-up page design
![Image](https://github.com/edust-org/edust/assets/106415501/f7f2fc3a-7c12-4d31-b626-6d35092f4048)

**Comment by sheik-mostafizur** [comment]
### Update the form design

Please update the form design to ensure it meets the best standards for our needs. Make any necessary adjustments to make it as effective and user-friendly as possible.

![Image](https://github.com/user-attachments/assets/f8571a39-51e2-43ca-93c9-0c13e54b0238)

**Comment by FollowNaim** [comment]
Hey, I'm on it and working on the form design updates. Will share progress soon.

**Comment by sheik-mostafizur** [comment]
We are waiting for your contribution

**Comment by FollowNaim** [comment]
I’ve opened a pull request (#36 ). Please review the changes.
