### ISSUE TITLE
With my solid experience and passion for technology, I am enthusiastic about the opportunity to contribute to your team.

### ISSUE THREAD

**Issue by johnsmith0212** [edust-org/edust#12]
Hi, I'm Ethan Tan, a web full-stack and blockchain developer with extensive experience spanning over 8 years. I specialize in developing resilient, scalable web applications and state-of-the-art blockchain solutions. My expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, ensures I deliver premium, secure, and efficient solutions tailored to your specific needs.

**Comment by sheik-mostafizur** [comment]
Sorry for being late I didn't expect your message and am very happy to see the message.

Please join our [Discord Server Edust Org](https://discord.gg/TmuwKa3H)

**Comment by sheik-mostafizur** [comment]
If you have any questions, please ask our [Discussions](https://github.com/edust-org/edust/discussions).
